const { DataTypes } = require("sequelize");
const { sequelize } = require("../sequelize");

const Businesses_2025 = sequelize.define(
  "Businesses_2025",
  {
    computer_no: DataTypes.STRING,
    status_of_permit: DataTypes.STRING,
    date_of_print_release: DataTypes.STRING,
    bin: DataTypes.STRING,
    application_type: DataTypes.STRING,
    first_name: DataTypes.STRING,
    middle_name: DataTypes.STRING,
    last_name: DataTypes.STRING,
    complete_owners_name: DataTypes.STRING,
    name_of_owner_amendment: DataTypes.STRING,
    business_name: DataTypes.STRING,
    contact_no: DataTypes.STRING,
    business_name_amendment: DataTypes.STRING,
    dti_registration_no: DataTypes.STRING,
    dti_date_of_registration: DataTypes.STRING,
    business_address: DataTypes.STRING,
    business_address_amendment: DataTypes.STRING,
    barangay_name: DataTypes.STRING,
    barangay_bracket: DataTypes.STRING,
    business_tin: DataTypes.STRING,
    kind_of_org: DataTypes.STRING,
    application_date: DataTypes.STRING,
    business_tax: DataTypes.STRING,
    mayors_permit_fee: DataTypes.STRING,
    total_barangay_fee: DataTypes.STRING,
    occupational_fee: DataTypes.STRING,
    health_cert_fee: DataTypes.STRING,
    health_cert_sworn_fee: DataTypes.STRING,
    swm_garbage_fee: DataTypes.STRING,
    sanitary_inspection_fee: DataTypes.STRING,
    building_inspection_fee: DataTypes.STRING,
    mechanical_inspection_fee: DataTypes.STRING,
    electrical_inspection_fee: DataTypes.STRING,
    signboard_billboard_renewal: DataTypes.STRING,
    electronic_inspection_fee: DataTypes.STRING,
    service_unit_license_fee: DataTypes.STRING,
    service_unit_mayors_permit_fee: DataTypes.STRING,
    surcharge: DataTypes.STRING,
    interest: DataTypes.STRING,
    tinplate_fee: DataTypes.STRING,
    sticker_fee: DataTypes.STRING,
    verification_fee: DataTypes.STRING,
    zoning_fee: DataTypes.STRING,
    cenro_fee: DataTypes.STRING,
    swm_fee_cert: DataTypes.STRING,
    vet_fee: DataTypes.STRING,
    fixed_tax: DataTypes.STRING,
    unpaid_months: DataTypes.STRING,
    essential_permit: DataTypes.STRING,
    essential_tax: DataTypes.STRING,
    add_business_tax: DataTypes.STRING,
    add_business_permit: DataTypes.STRING,
    add_barangay_fee: DataTypes.STRING,
    add_business_fixed: DataTypes.STRING,
    total_charges_cost: DataTypes.STRING,
    total_tax_with_fees_and_tax: DataTypes.STRING,
    total_amount_due: DataTypes.STRING,
    total_permit_fee: DataTypes.STRING,
    total_annual_inspection_cost: DataTypes.STRING,
    total_fixed_tax: DataTypes.STRING,
    mode_of_payment: DataTypes.STRING,
    total_tax_payment: DataTypes.STRING,
    buss_line: DataTypes.STRING,
    buss_line_code: DataTypes.STRING,
    sub_category: DataTypes.STRING,
    business_line: DataTypes.STRING,
    sub_category2: DataTypes.STRING,
    psic_code: DataTypes.STRING,
    no_units: DataTypes.STRING,
    capitalization_essential: DataTypes.STRING,
    total_gross_essential: DataTypes.STRING,
    non_essential: DataTypes.STRING,
    total_gross_non_essential: DataTypes.STRING,
    total_gross_sales_2025: DataTypes.STRING,
    capitalization_essential2: DataTypes.STRING,
    total_gross_essential2: DataTypes.STRING,
    non_essential2: DataTypes.STRING,
    total_gross_non_essential2: DataTypes.STRING,
    male: DataTypes.STRING,
    female: DataTypes.STRING,
    total: DataTypes.STRING,
    payors_name: DataTypes.STRING,
    date_paid_1: DataTypes.STRING,
    date_paid_2: DataTypes.STRING,
    date_paid_3: DataTypes.STRING,
    date_paid_4: DataTypes.STRING,
    mode_payment: DataTypes.STRING,
    or_number_1: DataTypes.STRING,
    or_number_2: DataTypes.STRING,
    or_number_3: DataTypes.STRING,
    or_number_4: DataTypes.STRING,
    cheque_no_1: DataTypes.STRING,
    cheque_no_2: DataTypes.STRING,
    cheque_no_3: DataTypes.STRING,
    cheque_no_4: DataTypes.STRING,
    cheque_rec: DataTypes.STRING,
    bank_branch: DataTypes.STRING,
    amount_1: DataTypes.STRING,
    amount_2: DataTypes.STRING,
    amount_3: DataTypes.STRING,
    amount_4: DataTypes.STRING,
    total_amount: DataTypes.STRING,
    cash_rec: DataTypes.STRING,
    amount_in_words: DataTypes.STRING,
    owners_address: DataTypes.STRING,
    name_of_owner_address_amendment: DataTypes.STRING,
    additional_line_of_business: DataTypes.STRING,
    amendment_of_nature_of_business: DataTypes.STRING,
    remarks: DataTypes.STRING,
  },
  {
    tableName: "Businesses_2025",
    timestamps: true,
  }
);

module.exports = Businesses_2025;
